kind = "mobile"
previewPath = "/"
title = "GlucoApp"
version = "1.0.0"
id = "artifacts/glucoapp"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24619

[services.development]
run = "pnpm --filter @workspace/glucoapp run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/glucoapp", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/glucoapp", "run", "serve" ]

[services.env]
PORT = "24619"
BASE_PATH = "/"
